# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 05:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('link', models.URLField(verbose_name='图片链接地址')),
                ('image', models.ImageField(upload_to='image', verbose_name='上传图片')),
            ],
            options={
                'verbose_name_plural': '首页Banner图片',
                'verbose_name': '首页Banner图片',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='文章类别')),
                ('alias', models.CharField(blank=True, max_length=40, verbose_name='类别别名')),
            ],
            options={
                'verbose_name_plural': '文章类别',
                'verbose_name': '文章类别',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='菜单项标题')),
                ('position', models.IntegerField(default=500, verbose_name='菜单项位置')),
                ('link_url', models.CharField(help_text='内部Url或者外部Url', max_length=100, verbose_name='菜单项URL')),
                ('login_required', models.BooleanField(help_text='是否仅对已登陆用户可见', verbose_name='已登陆用户可见？')),
                ('anonymous_only', models.BooleanField(help_text='是否仅对匿名用户可见', verbose_name='匿名用户可见?')),
            ],
            options={
                'verbose_name_plural': '菜单项',
                'verbose_name': '菜单项',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='数字越少越靠前', verbose_name='导航位置')),
                ('name', models.CharField(help_text='在页面显示的导航名', max_length=20, verbose_name='导航名')),
                ('base_url', models.CharField(blank=True, help_text='导航Url', max_length=20, null=True, verbose_name='导航Url')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='导航别名')),
                ('status', models.BooleanField(help_text='编辑确定是否启用该导航', verbose_name='是否启用')),
            ],
            options={
                'verbose_name_plural': '菜单',
                'verbose_name': '菜单',
            },
        ),
        migrations.CreateModel(
            name='NewsArtile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.BooleanField(help_text='创建的文章是否在前台展示！', verbose_name='发布？')),
                ('position', models.IntegerField(help_text='数字越少越靠前', verbose_name='文章排序')),
                ('isnew', models.BooleanField(help_text='创建的文章是否显示new标志', verbose_name='新文章？')),
                ('headimg', models.ImageField(upload_to='image', verbose_name='文章缩略图')),
                ('abstract', ckeditor_uploader.fields.RichTextUploadingField(max_length=300, verbose_name='文章摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.Menus', verbose_name='导航栏目')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.Category', verbose_name='文章类别')),
            ],
            options={
                'verbose_name_plural': '新建文章',
                'verbose_name': '新建文章',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.Menus', verbose_name='菜单项'),
        ),
    ]
