# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('link', models.URLField(verbose_name='图片链接地址')),
                ('image', models.ImageField(upload_to='image', verbose_name='上传图片')),
            ],
            options={
                'verbose_name_plural': '首页Banner图片',
                'verbose_name': '首页Banner图片',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='文章类别')),
                ('alias', models.CharField(blank=True, max_length=40, verbose_name='类别别名')),
            ],
            options={
                'verbose_name_plural': '类别',
                'verbose_name': '类别',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='数字越少越靠前', verbose_name='导航位置')),
                ('name', models.CharField(help_text='在页面显示的导航名', max_length=20, verbose_name='导航名')),
                ('url', models.CharField(help_text='导航Url', max_length=20, verbose_name='导航Url')),
                ('status', models.BooleanField(help_text='编辑确定是否启用该导航', verbose_name='是否启用')),
            ],
            options={
                'verbose_name_plural': '菜单',
                'verbose_name': '菜单',
            },
        ),
        migrations.CreateModel(
            name='NewsArtile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.BooleanField(help_text='创建的文章是否在前台展示！', verbose_name='发布？')),
                ('position', models.IntegerField(help_text='数字越少越靠前', verbose_name='文章排序')),
                ('isnew', models.BooleanField(help_text='创建的文章是否显示new标志', verbose_name='新文章？')),
                ('headimg', models.ImageField(upload_to='image', verbose_name='文章缩略图')),
                ('abstract', models.TextField(max_length=300, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name_plural': '新建文章',
                'verbose_name': '新建文章',
            },
        ),
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='文章别名')),
            ],
            options={
                'verbose_name_plural': '别名',
                'verbose_name': '别名',
            },
        ),
        migrations.CreateModel(
            name='ChildMenus',
            fields=[
                ('menus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guanwang.Menus')),
            ],
            options={
                'verbose_name_plural': '二级菜单',
                'verbose_name': '二级菜单',
            },
            bases=('guanwang.menus',),
        ),
        migrations.AddField(
            model_name='newsartile',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.Menus', verbose_name='导航ID'),
        ),
        migrations.AddField(
            model_name='newsartile',
            name='slug',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guanwang.Slug', verbose_name='文章别名'),
        ),
        migrations.AddField(
            model_name='newsartile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.Category', verbose_name='文章类别'),
        ),
        migrations.AddField(
            model_name='menus',
            name='code',
            field=models.ForeignKey(help_text='导航那个类别的文章', on_delete=django.db.models.deletion.CASCADE, to='guanwang.Category', verbose_name='导航类别'),
        ),
        migrations.AddField(
            model_name='childmenus',
            name='child_parentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildMenus_childParentId', to='guanwang.Menus', verbose_name='父导航ID'),
        ),
    ]
