# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guanwang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsartile',
            name='type',
        ),
        migrations.AlterField(
            model_name='newsartile',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.MenuItem', verbose_name='导航栏目'),
        ),
    ]
