# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guanwang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章类别', 'verbose_name_plural': '文章类别'},
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': '一级菜单', 'verbose_name_plural': '一级菜单'},
        ),
        migrations.AlterModelOptions(
            name='slug',
            options={'verbose_name': '文章别名', 'verbose_name_plural': '文章别名'},
        ),
        migrations.AlterField(
            model_name='newsartile',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanwang.ChildMenus', verbose_name='导航栏目'),
        ),
    ]
